maintainer: 'Kris Gray<kgray@justise.com>'
name: 'Justise.com'

pages:
    /:
        # I would expect this to allow me to specify
        # layout: 'src/theme/layouts/base.njk'
        content: 'homepage.md'

projects: []
